[package]
name = "tempo-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "tempo"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tempo-core = { path = "../tempo-core" }
tempo-ipc = { path = "../tempo-ipc" }
